# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KZy7XBIpgoAGPLvDRMMnvgCN9tNdpHJuc2sPUcQTKvfJcUJYcRvc6NpYHz0EXAEOQ+lkK4mMgVQfuSHJECvejrnoPBEmLXWHUdtgfOid1ldjczZeQa5vcJ11lJcDJ++KHnjGPq0jOVmxyofL051HajKtZ5xnUkOl9wQjUW/Ur0a78UhpJEcgjGN0y25LsOZk1ork8s63k6eT897gYKY+al4Wp6o7pQ1x1bHnK4yvYQyFe+9HItEzGE5mdHJ5dEJxhbWK2nwAKpzwe8fe4k89YHWkLNwfyIUnKr252nPFF5pL8YoBuPK5ot8cAcUhEYeOOXDVhKtz4BfZ5zZf6/j6BjoB6m+RB755mjc2/D1/c9Tzh5bAIAQUJ+ChDHWBn9D8j5WsyDE0Mn9dWQAWtbDm0rwlRdo4IFl0BX0ITogeoPcN9kuK15+Ofcy9ydUUWtODLzxIMC2pLKfKiNTUVx19zclGto9CzZixqROI8OxYi8QcxgGPtmNbln6ssguYghBXrWWNODaBiA1cx2o+aSCt1bV7/UDsqmYcyKHFBMbukUu+iscGr4KEO9l69zbDCWwRC25/ZukpLOC1/8ZzbRd/Y92+tokEQjkuepuQhDe1QZAPzOkvjZMDGI+WzOvWVCeHn9kbA18eprJktweZw7PEfNk0uHvLSw92vC5Y0oyKNy0="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
