travis:
  secure:
    BINSTAR_TOKEN: KZy7XBIpgoAGPLvDRMMnvgCN9tNdpHJuc2sPUcQTKvfJcUJYcRvc6NpYHz0EXAEOQ+lkK4mMgVQfuSHJECvejrnoPBEmLXWHUdtgfOid1ldjczZeQa5vcJ11lJcDJ++KHnjGPq0jOVmxyofL051HajKtZ5xnUkOl9wQjUW/Ur0a78UhpJEcgjGN0y25LsOZk1ork8s63k6eT897gYKY+al4Wp6o7pQ1x1bHnK4yvYQyFe+9HItEzGE5mdHJ5dEJxhbWK2nwAKpzwe8fe4k89YHWkLNwfyIUnKr252nPFF5pL8YoBuPK5ot8cAcUhEYeOOXDVhKtz4BfZ5zZf6/j6BjoB6m+RB755mjc2/D1/c9Tzh5bAIAQUJ+ChDHWBn9D8j5WsyDE0Mn9dWQAWtbDm0rwlRdo4IFl0BX0ITogeoPcN9kuK15+Ofcy9ydUUWtODLzxIMC2pLKfKiNTUVx19zclGto9CzZixqROI8OxYi8QcxgGPtmNbln6ssguYghBXrWWNODaBiA1cx2o+aSCt1bV7/UDsqmYcyKHFBMbukUu+iscGr4KEO9l69zbDCWwRC25/ZukpLOC1/8ZzbRd/Y92+tokEQjkuepuQhDe1QZAPzOkvjZMDGI+WzOvWVCeHn9kbA18eprJktweZw7PEfNk0uHvLSw92vC5Y0oyKNy0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
